### PR TITLE
add ambience sound to test_chamber_08/09

### PR DESCRIPTION
**Pull request by hackgrid**

### CODE REVIEW

**Comment by hackgrid** [comment]
09 really needs a START category though, that immediately starts the ambience sounds after exiting the elevator, like the other levels. I never worked with Blender before though.

**Comment by mwpenny** [comment]
Great, thanks! These two chambers need some more polish since they are what James was working on when he stopped.

There's a conflict after the last merge, but after that is resolved this looks good to go.

If you're interested in adding a `START` cutscene to the chamber, you just need to place a new [trigger](https://github.com/mwpenny/portal64-still-alive/blob/master/documentation/levels/level_objects/trigger.md) (more context in the [level objects README](https://github.com/mwpenny/portal64-still-alive/blob/master/documentation/levels/level_objects/README.md)). If not, no worries.

**Comment by mwpenny** [comment]
I resolved the merge conflict, and before I go back to other chamber 14 changes I added a `START` trigger so the ambience can begin playing at the elevator.

Thanks!

**Comment by mwpenny** [comment]
I updated all levels to start the ambient sound at the elevator, adding `START` triggers where necessary.

**Comment by hackgrid** [comment]
Thank you, I still was busy with other things! :)

**Pull request merged**
