### PR TITLE
Documentation fix

### PR DESCRIPTION
**Pull request by FoxbitDreamtail**
Edits Welcome
I have to the best of my ability added a separate set of instructions which should allow for building this project without snap on Ubuntu based distros.

### CODE REVIEW

**Comment by hackgrid** [comment]
I doubt anybody would want to install Steam to install Blender?? Steam is
closed source too you know, why is that supposed to be better than snap?
Way worse in my opinion.
Snap is available on all major distros too. But this topic is not important
at all, everybody can install blender 3.6 however they want and then edit
the BLENDER_36 environment variable.

Foxbit ***@***.***> schrieb am Mo., 12. Aug. 2024, 02:16:

**Comment by FoxbitDreamtail** [comment]
I was saying Steam because if you're installing Portal, you have to have
Steam installed in order to do that in the first place. Would it not make
sense to, on the exact same system, that you have to install Portal on, be
able to obtain a copy of a required software as well? That's why I'm
asking, Also, many people justifiably hate Snap. It's not just that it's
closed source and proprietary, it's that there are other options that are
far better than Snap. Plus, the fact that you have to have steam installed
in the first place to get the files for portal means that this wouldn't be
an additional package manager install.

**Comment by FoxbitDreamtail** [comment]
basically, steam is already installed, why not use it for people who do NOT want snap on their systems.

**Comment by FoxbitDreamtail** [comment]
I mean at least I didn't add that you're all snap loving shills, I was being respectful. You could always add unofficial in brackets. That is your option to do. You have edit access.

**Comment by mwpenny** [comment]
> I doubt anybody would want to install Steam to install Blender

I personally wouldn't install it this way but I can see why someone might want to. However, documenting each system configuration that comes up like this is a slippery slope.

Case in point: the new document has a lot of duplication with the existing ones, meaning they can easily diverge over time. Not to mention the extra work of maintaining documentation for an additional platform. It's the same reason there's no document for Arch, Fedora, Windows, etc.

We should stay away from going over all of the possible ways to install dependencies and just focus on a coherent generic set of steps that will work for most people. Anyone who wants to get Blender from somewhere else, for example, will know where they want to get it from. We can just explain how to tell the build where it is (environment variable). The build itself doesn't care how you installed it.

So, for example, we could have some platform-agnostic documentation like "install dependencies X Y Z using your package manager", "install Blender 3.6 using your preferred means and update the environment variable", etc. Then give a few common examples, but not an exhaustive list. 

More thoughts here: https://github.com/mwpenny/portal64-still-alive/issues/80#issuecomment-2285323214.

**Comment by FoxbitDreamtail** [comment]
> So, for example, we could have some platform-agnostic documentation like "install dependencies X Y Z using your package manager", "install Blender 3.6 using your preferred means and update the environment variable", etc. Then give a few common examples, but not an exhaustive list.

My apologies if I wasn't clear, I'll close this poll request with this but my primary problem was that snap seemed like the only option from how it was written and when I showed other ways of doing it, hackgrid shrugged them off as "and so?" comments which made me feel inadequate as a contributor.... my primary problem isn't that snap is being used, it's that it is being shown as the only way to do things which clearly is and was not true.

**Comment by hackgrid** [comment]
What are you talking about, I told you from the start you can install
Blender however you would like, but had to edit the Makefile or environment
variable.

https://github.com/mwpenny/portal64-still-alive/issues/80#issuecomment-2282741766

**Comment by FoxbitDreamtail** [comment]
> What are you talking about, I told you from the start you can install Blender however you would like, but had to edit the Makefile or environment variable. [#80 (comment)](https://github.com/mwpenny/portal64-still-alive/issues/80#issuecomment-2282741766)

you didn't tell me how to edit the Makefile or where to look! I'm not a developer, I am a fan/tester who sometimes likes getting my hands dirty by compiling projects from source, that doesn't make me a developer in any capacity.

**Comment by mwpenny** [comment]
Sounds like there was some confusion but we're on the same page now. I think we can leave it at that.

I can understand how as a non-developer things could get confusing, but compiling is intended for those with some familiarity. Wanting to learn is good, but the project's docs can only explain things up to a certain point. Their scope is limited to this project.

The fundamentals are better explained elsewhere anyway. For example: https://wiki.archlinux.org/title/Environment_variables. If you're not sure about something then please search or ask before assuming.

I will eventually switch to CMake and update the docs, which should make the build less error-prone.

**Comment by FoxbitDreamtail** [comment]
> I will eventually switch to CMake and update the docs, which should make the build less error-prone.

thank you for understanding and I can't wait for the easier build process! (not that the current is too difficult)

**Comment by mwpenny** [comment]
The game is now built using CMake, along with many build improvements. One such improvement is that it will automatically find Blender on your system (or you can override it with a specific path).

I've updated the build documentation.

**Pull request closed without merging**
